version: '3'
services:
  n8n:
    image: n8nio/n8n
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${DOMAIN}
      - N8N_PROTOCOL=https
      - WEBHOOK_TUNNEL_URL=https://${DOMAIN}/
      - GENERIC_TIMEZONE=Asia/Jakarta
    volumes:
      - ./.n8n:/home/node/.n8n
      - ./rclone:/rclone
    command: sh /app/start.sh
